### ISSUE TITLE
it didn't work on win 10

### ISSUE THREAD

**Issue by 55cc** [zapty/echoipdns#3]
C:\WINDOWS\system32>echoipdns loc -f 127.0.0.1
Wed Mar 13 2019 17:13:43        Starting process 528
Wed Mar 13 2019 17:13:43        echoipdns listening on port 53, forwards to 127.0.0.1
Wed Mar 13 2019 17:13:43        echoipdns forwarding domains containing words loc to 127.0.0.1 or embedded ip separated by - in the domain name
An error occured. { Error: spawn growlnotify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:C:\\Users\\Jim\\AppData\\Roaming\\npm\\node_modules\\echoipdns\\olodum.png',
     'Starting process 528',
     '/t:Fasterize Local DNS Server' ] }
An error occured. { Error: spawn growlnotify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:C:\\Users\\Jim\\AppData\\Roaming\\npm\\node_modules\\echoipdns\\olodum.png',
     'echoipdns listening on port 53, forwards to 127.0.0.1',
     '/t:Fasterize Local DNS Server' ] }
An error occured. { Error: spawn growlnotify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:C:\\Users\\Jim\\AppData\\Roaming\\npm\\node_modules\\echoipdns\\olodum.png',
     'echoipdns forwarding domains containing words loc to 127.0.0.1 or embedded ip separated by - in the domain name',
     '/t:Fasterize Local DNS Server' ] }

**Comment by 55cc** [comment]
没人?
